### ISSUE TITLE
Carpetas para cada tipo de fichero

### ISSUE THREAD

**Issue by damiancastelao** [asierraperez/PROG-Ejercicios20#1]
Los distintos tipos de ficheros tienes que organizarlos en distintas carpetas:

- Los html pueden quedar en el raíz
- Los ficheros js -> carpeta scripts
- Los ficheros css -> carpeta styles
- Imagenes, videos -> otra carpeta como images, videos, media o resources

**Comment by asierraperez** [comment]
Listo, cada archivo está en su carpeta

**Comment by damiancastelao** [comment]
Muy, procura hacer este esquema siempre en los proyectos.
